---
- name: Copy books from stage->live
  hosts: all
  tasks:

    - name: set up tmp directory
      command: "rm -rf /usr/local/liberator_output_tmp"

    - name: Copy books from stage into tmp directory
      command: "cp -r /usr/local/liberator_stage/output /usr/local/liberator_output_tmp"

    #need to use shell (not command) here as command seems to choke on the delete
    - name: Delete bookmarks in tmp
      shell: 
        cmd: rm /usr/local/liberator_output_tmp/*/*.bookmark

    - name: Find bookmarks from live 
      find:
        paths: /usr/local/liberator/output
        patterns: "*.bookmark"
        recurse: yes
      register: bookmarks

    - name: Copy live bookmarks -> tmp  
      copy:
        src: "{{ item.path }}"
        dest: "{{ ( '/usr/local/liberator_output_tmp', item.path|relpath('/usr/local/liberator/output') ) | path_join }}"
        remote_src: yes
      loop: "{{ bookmarks.files }}"

    - name: Set permissions for copied books
      command: "chmod 777 -R /usr/local/liberator_output_tmp"

    - name: Back up old output directory
      command: "mv /usr/local/liberator/output /usr/local/liberator/output_bak"

    - name: Deploy new output directory
      command: "mv /usr/local/liberator_output_tmp /usr/local/liberator/output"
#    - name: debug 
#      ansible.builtin.debug:
#        msg: "{{ bookmarks.files }}"